"""
artifact_compiler/docx_compiler.py — PSU-styled approval-note DOCX generator.

Uses docxtpl (Jinja2-based) with an embedded template approach.
Template is generated programmatically via python-docx — no external .docx file required.

All outputs go to data/artifacts/ only. Safe filenames generated by application.
Provenance fields: request_id, timestamp, evidence_ids, label, model_role, compiler_version.
Disclaimer on every doc: "Prototype output — not an engineering approval or statutory determination."
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

from ..config import BASE_DIR

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "Prototype output — not an engineering approval or statutory determination. "
    "This document was generated by the MRPL Sovereign AI Workbench demonstration system. "
    "Do not use for any operational, regulatory, or engineering decision."
)
ARTIFACT_DIR = BASE_DIR / "data" / "artifacts"
COMPILER_VERSION = "docx_compiler-0.1.0 / python-docx-1.2.0 / docxtpl-0.20.2"


def generate(
    *,
    query: str,
    evidence: list[dict],
    session_id: str,
    model_role: str | None,
    label: str = "SYNTHETIC",
    request_id: str | None = None,
) -> dict[str, Any]:
    """
    Generate a PSU-styled approval-note .docx.

    Returns:
        {"status": "ok", "file_path": str, "provenance": dict}
        or {"status": "error", "error": str}
    """
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    request_id = request_id or str(uuid.uuid4())
    ts = datetime.now(timezone.utc)
    safe_name = f"approval_note_{request_id[:8]}_{ts.strftime('%Y%m%d_%H%M%S')}.docx"
    out_path = ARTIFACT_DIR / safe_name

    # Security: ensure output is inside artifact dir
    try:
        out_path.resolve().relative_to(ARTIFACT_DIR.resolve())
    except ValueError:
        return {"status": "error", "error": "path traversal rejected"}

    try:
        doc = Document()

        # --- Title ---
        title = doc.add_heading("MRPL Sovereign AI Workbench", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        sub = doc.add_heading("Equipment Inspection Approval Note — DEMO", level=1)
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # --- Disclaimer (prominent) ---
        disclaimer_para = doc.add_paragraph()
        disclaimer_run = disclaimer_para.add_run(DISCLAIMER)
        disclaimer_run.bold = True
        disclaimer_run.font.color.rgb = RGBColor(0xC0, 0x00, 0x00)
        disclaimer_run.font.size = Pt(9)
        disclaimer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()  # spacer

        # --- Metadata table ---
        meta_table = doc.add_table(rows=7, cols=2)
        meta_table.style = "Table Grid"
        meta_data = [
            ("Document ID", request_id),
            ("Generated", ts.strftime("%Y-%m-%d %H:%M:%S UTC")),
            ("Session ID", session_id),
            ("Operator Query", query[:200]),
            ("Data Label", label),
            ("Model Role", model_role or "N/A"),
            ("Compiler", COMPILER_VERSION),
        ]
        for i, (key, val) in enumerate(meta_data):
            row = meta_table.rows[i]
            row.cells[0].text = key
            row.cells[1].text = val
            row.cells[0].paragraphs[0].runs[0].bold = True

        doc.add_paragraph()

        # --- Query section ---
        doc.add_heading("Query", level=2)
        doc.add_paragraph(query)

        # --- Evidence section ---
        doc.add_heading("Retrieved Evidence", level=2)
        if evidence:
            for i, ev in enumerate(evidence[:5], 1):
                p = doc.add_paragraph(style="List Number")
                run = p.add_run(
                    f"[{ev.get('doc_id', 'unknown')}] "
                    f"Score: {ev.get('score', 0):.4f} — "
                    f"{ev.get('text_preview', '')[:300]}"
                )
                run.font.size = Pt(9)
        else:
            doc.add_paragraph("No evidence retrieved (INSUFFICIENT_EVIDENCE or RAG not invoked).")

        # --- Capability limitations ---
        doc.add_heading("Capability Limitations", level=2)
        limitations = [
            "Vision: VISION_UNAVAILABLE — VL model not loaded (GGUF not downloaded).",
            "Sandbox: DEGRADED_SANDBOX — Docker not installed; in-process exec with allowlist only.",
            "Model swap latency: UNMEASURED — GGUF files not downloaded.",
            "Corpus: 9 vectors (minimal demo set) — not production coverage.",
        ]
        for lim in limitations:
            doc.add_paragraph(lim, style="List Bullet")

        # --- Footer disclaimer again ---
        doc.add_paragraph()
        footer = doc.add_paragraph(DISCLAIMER)
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

        doc.save(str(out_path))
        logger.info("DOCX generated: %s", out_path.name)

    except Exception as exc:
        logger.error("DOCX generation failed: %s", exc)
        return {"status": "error", "error": str(exc)}

    provenance = {
        "request_id": request_id,
        "session_id": session_id,
        "timestamp_utc": ts.isoformat(),
        "evidence_ids": [ev.get("doc_id") for ev in evidence],
        "label": label,
        "model_role": model_role,
        "compiler": COMPILER_VERSION,
        "output_file": safe_name,
        "disclaimer": DISCLAIMER,
    }
    return {
        "status": "ok",
        "file_path": str(out_path),
        "file_name": safe_name,
        "provenance": provenance,
    }
